"""initial_migrate

Revision ID: 6a4e5ccb2054
Revises: 
Create Date: 2023-03-19 13:50:49.501842

"""
from alembic import op
import sqlalchemy as sa

from models.base_model import Id

# revision identifiers, used by Alembic.
revision = '6a4e5ccb2054'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('telegram_id', sa.BigInteger(), nullable=False),
        sa.Column('download_count', sa.BigInteger(), nullable=True),
        sa.Column('id', Id(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
