"""configure book inner info

Revision ID: 1777d4da6778
Revises: 83b538f15722
Create Date: 2024-06-30 16:04:57.073112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1777d4da6778'
down_revision: Union[str, None] = '83b538f15722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_inner_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=25), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False, comment='Telegram file id'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_inner_info_book_id'), 'book_inner_info', ['book_id'], unique=False)
    op.create_table('book_user_association',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book_inner_info.book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('book_id', 'user_id')
    )
    op.drop_table_comment(
        'libseqname',
        existing_comment='Список форм (1-100) и названий сериа',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'libseqname',
        'Список форм (1-100) и названий сериа',
        existing_comment=None,
        schema=None
    )
    op.drop_table('book_user_association')
    op.drop_index(op.f('ix_book_inner_info_book_id'), table_name='book_inner_info')
    op.drop_table('book_inner_info')
    # ### end Alembic commands ###
