"""essage

Revision ID: 83b538f15722
Revises: 
Create Date: 2024-05-12 12:42:41.763526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83b538f15722'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libavtor',
    sa.Column('BookId', sa.Integer(), nullable=False),
    sa.Column('AvtorId', sa.Integer(), nullable=False),
    sa.Column('Pos', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('BookId', 'AvtorId')
    )
    op.create_index('iav', 'libavtor', ['AvtorId'], unique=False)
    op.create_table('libavtorname',
    sa.Column('AvtorId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FirstName', sa.String(length=99), nullable=False),
    sa.Column('MiddleName', sa.String(length=99), nullable=False),
    sa.Column('LastName', sa.String(length=99), nullable=False),
    sa.Column('NickName', sa.String(length=33), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Homepage', sa.String(length=255), nullable=False),
    sa.Column('Gender', sa.String(length=1), nullable=False),
    sa.Column('MasterId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('AvtorId')
    )
    op.create_index('FirstName', 'libavtorname', ['FirstName'], unique=False, mysql_length=20)
    op.create_index('Homepage', 'libavtorname', ['Homepage'], unique=False)
    op.create_index('LastName', 'libavtorname', ['LastName'], unique=False, mysql_length=20)
    op.create_index('MasterId', 'libavtorname', ['MasterId'], unique=False)
    op.create_index('email', 'libavtorname', ['Email'], unique=False)
    op.create_index('uid', 'libavtorname', ['uid'], unique=False)
    op.create_table('libbannotations',
    sa.Column('BookId', sa.Integer(), nullable=False),
    sa.Column('nid', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Body', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('BookId'),
    mysql_collate='utf8mb3_unicode_ci'
    )
    op.create_table('libbook',
    sa.Column('BookId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FileSize', sa.Integer(), nullable=False),
    sa.Column('Time', sa.DateTime(), nullable=False),
    sa.Column('Title', sa.String(length=254), nullable=False),
    sa.Column('Title1', sa.String(length=254), nullable=False),
    sa.Column('Lang', sa.String(length=3), nullable=False),
    sa.Column('LangEx', sa.SmallInteger(), nullable=False),
    sa.Column('SrcLang', sa.String(length=3), nullable=False),
    sa.Column('FileType', sa.String(length=4), nullable=False),
    sa.Column('Encoding', sa.String(length=32), nullable=False),
    sa.Column('Year', sa.SmallInteger(), nullable=False),
    sa.Column('Deleted', sa.String(length=1), nullable=False),
    sa.Column('Ver', sa.String(length=8), nullable=False),
    sa.Column('FileAuthor', sa.String(length=64), nullable=False),
    sa.Column('N', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.String(length=255), nullable=False),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('Modified', sa.DateTime(), server_default='2009-11-29 05:00:00', nullable=False),
    sa.Column('pmd5', sa.String(length=32), nullable=False),
    sa.Column('InfoCode', sa.SmallInteger(), nullable=False),
    sa.Column('Pages', sa.Integer(), nullable=False),
    sa.Column('Chars', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('BookId'),
    sa.UniqueConstraint('Deleted', 'BookId', name='BookDel'),
    sa.UniqueConstraint('md5'),
    mysql_collate='utf8mb3_unicode_ci'
    )
    op.create_index('Deleted', 'libbook', ['Deleted'], unique=False)
    op.create_index('FileAuthor', 'libbook', ['FileAuthor'], unique=False)
    op.create_index('FileSize', 'libbook', ['FileSize'], unique=False)
    op.create_index('FileType', 'libbook', ['FileType'], unique=False)
    op.create_index('Lang', 'libbook', ['Lang'], unique=False)
    op.create_index('N', 'libbook', ['N'], unique=False)
    op.create_index('Title', 'libbook', ['Title'], unique=False)
    op.create_index('Title1', 'libbook', ['Title1'], unique=False)
    op.create_index('Year', 'libbook', ['Year'], unique=False)
    op.create_table('libfilename',
    sa.Column('BookId', sa.Integer(), nullable=False),
    sa.Column('FileName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('BookId'),
    sa.UniqueConstraint('FileName'),
    sa.UniqueConstraint('FileName', name='file_name'),
    mysql_charset='latin1'
    )
    op.create_table('libgenre',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BookId', sa.Integer(), nullable=False),
    sa.Column('GenreId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('BookId', 'GenreId', name='u'),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ibook', 'libgenre', ['BookId'], unique=False)
    op.create_index('igenre', 'libgenre', ['GenreId'], unique=False)
    op.create_table('libgenrelist',
    sa.Column('GenreId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('GenreCode', sa.String(length=45), nullable=False),
    sa.Column('GenreDesc', sa.String(length=99), nullable=False),
    sa.Column('GenreMeta', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('GenreId', 'GenreCode'),
    mysql_collate='utf8mb3_unicode_ci'
    )
    op.create_index('meta', 'libgenrelist', ['GenreMeta'], unique=False)
    op.create_table('libjoinedbooks',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Time', sa.TIMESTAMP(), nullable=False),
    sa.Column('BadId', sa.Integer(), nullable=False),
    sa.Column('GoodId', sa.Integer(), nullable=False),
    sa.Column('realId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('BadId')
    )
    op.create_index('GoodId', 'libjoinedbooks', ['GoodId'], unique=False)
    op.create_index('Time', 'libjoinedbooks', ['Time'], unique=False)
    op.create_index('realId', 'libjoinedbooks', ['realId'], unique=False)
    op.create_table('librate',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BookId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('Rate', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('ID', 'BookId'),
    sa.UniqueConstraint('BookId', 'UserId', name='BookId_UserId'),
    mysql_charset='latin1'
    )
    op.create_index('BookId', 'librate', ['BookId'], unique=False)
    op.create_index('UserId', 'librate', ['UserId'], unique=False)
    op.create_table('libseq',
    sa.Column('BookId', sa.Integer(), nullable=False),
    sa.Column('SeqId', sa.Integer(), nullable=False),
    sa.Column('SeqNumb', sa.Integer(), nullable=False),
    sa.Column('Level', sa.SmallInteger(), nullable=False),
    sa.Column('Type', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('BookId', 'SeqId'),
    mysql_charset='latin1'
    )
    op.create_index('SeqId', 'libseq', ['SeqId'], unique=False)
    op.create_table('libseqname',
    sa.Column('SeqId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SeqName', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('SeqId'),
    sa.UniqueConstraint('SeqName'),
    sa.UniqueConstraint('SeqName', name='SeqName_2'),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_comment='Список форм (1-100) и названий сериа',
    mysql_engine='MyISAM'
    )
    op.create_table('users',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('libseqname')
    op.drop_index('SeqId', table_name='libseq')
    op.drop_table('libseq')
    op.drop_index('UserId', table_name='librate')
    op.drop_index('BookId', table_name='librate')
    op.drop_table('librate')
    op.drop_index('realId', table_name='libjoinedbooks')
    op.drop_index('Time', table_name='libjoinedbooks')
    op.drop_index('GoodId', table_name='libjoinedbooks')
    op.drop_table('libjoinedbooks')
    op.drop_index('meta', table_name='libgenrelist')
    op.drop_table('libgenrelist')
    op.drop_index('igenre', table_name='libgenre')
    op.drop_index('ibook', table_name='libgenre')
    op.drop_table('libgenre')
    op.drop_table('libfilename')
    op.drop_index('Year', table_name='libbook')
    op.drop_index('Title1', table_name='libbook')
    op.drop_index('Title', table_name='libbook')
    op.drop_index('N', table_name='libbook')
    op.drop_index('Lang', table_name='libbook')
    op.drop_index('FileType', table_name='libbook')
    op.drop_index('FileSize', table_name='libbook')
    op.drop_index('FileAuthor', table_name='libbook')
    op.drop_index('Deleted', table_name='libbook')
    op.drop_table('libbook')
    op.drop_table('libbannotations')
    op.drop_index('uid', table_name='libavtorname')
    op.drop_index('email', table_name='libavtorname')
    op.drop_index('MasterId', table_name='libavtorname')
    op.drop_index('LastName', table_name='libavtorname', mysql_length=20)
    op.drop_index('Homepage', table_name='libavtorname')
    op.drop_index('FirstName', table_name='libavtorname', mysql_length=20)
    op.drop_table('libavtorname')
    op.drop_index('iav', table_name='libavtor')
    op.drop_table('libavtor')
    # ### end Alembic commands ###
