"""initial

Revision ID: a30496b8811d
Revises: 
Create Date: 2024-05-12 07:11:18.655392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a30496b8811d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libjoinedbooks',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Time', sa.TIMESTAMP(), nullable=False),
    sa.Column('BadId', sa.Integer(), nullable=False),
    sa.Column('GoodId', sa.Integer(), nullable=False),
    sa.Column('realId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('BadId')
    )
    op.create_index('GoodId', 'libjoinedbooks', ['GoodId'], unique=False)
    op.create_index('Time', 'libjoinedbooks', ['Time'], unique=False)
    op.create_index('realId', 'libjoinedbooks', ['realId'], unique=False)
    op.create_table('librate',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BookId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('Rate', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('ID', 'BookId'),
    sa.UniqueConstraint('BookId', 'UserId', name='BookId_UserId'),
    mysql_charset='latin1'
    )
    op.create_index('BookId', 'librate', ['BookId'], unique=False)
    op.create_index('UserId', 'librate', ['UserId'], unique=False)
    op.create_table('libseq',
    sa.Column('BookId', sa.Integer(), nullable=False),
    sa.Column('SeqId', sa.Integer(), nullable=False),
    sa.Column('SeqNumb', sa.Integer(), nullable=False),
    sa.Column('Level', sa.SmallInteger(), nullable=False),
    sa.Column('Type', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('BookId', 'SeqId'),
    mysql_charset='latin1'
    )
    op.create_index('SeqId', 'libseq', ['SeqId'], unique=False)
    op.create_table('libseqname',
    sa.Column('SeqId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SeqName', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('SeqId'),
    sa.UniqueConstraint('SeqName'),
    sa.UniqueConstraint('SeqName', name='SeqName_2'),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_comment='Список форм (1-100) и названий сериа',
    mysql_engine='MyISAM'
    )
    op.create_table('users',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('libseqname')
    op.drop_index('SeqId', table_name='libseq')
    op.drop_table('libseq')
    op.drop_index('UserId', table_name='librate')
    op.drop_index('BookId', table_name='librate')
    op.drop_table('librate')
    op.drop_index('realId', table_name='libjoinedbooks')
    op.drop_index('Time', table_name='libjoinedbooks')
    op.drop_index('GoodId', table_name='libjoinedbooks')
    op.drop_table('libjoinedbooks')
    # ### end Alembic commands ###
