"""add book annotations

Revision ID: d43d5d4ff7f0
Revises: 2e3f7b9ad265
Create Date: 2024-05-06 18:50:58.121007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd43d5d4ff7f0'
down_revision: Union[str, None] = '2e3f7b9ad265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libbannotations',
    sa.Column('BookId', sa.Integer(), nullable=False),
    sa.Column('nid', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('BookId')
    )
    op.alter_column('libavtor', 'Pos',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_index('iav', table_name='libavtor')
    op.alter_column('libavtorname', 'Gender',
               existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=1),
               type_=sa.String(length=1),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('libavtorname', 'MasterId',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_index('email', table_name='libavtorname')
    op.alter_column('libbook', 'Time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('libbook', 'Lang',
               existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'ru'"))
    op.alter_column('libbook', 'LangEx',
               existing_type=mysql.SMALLINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('libbook', 'SrcLang',
               existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('libbook', 'FileType',
               existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=4),
               type_=sa.String(length=4),
               existing_nullable=False)
    op.alter_column('libbook', 'Year',
               existing_type=mysql.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('libbook', 'Deleted',
               existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=1),
               type_=sa.String(length=1),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('libbook', 'md5',
               existing_type=sa.BINARY(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('libbook', 'Modified',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("'2009-11-29 05:00:00'"))
    op.alter_column('libbook', 'pmd5',
               existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=32),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('libbook', 'InfoCode',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index('BookDel', table_name='libbook')
    op.drop_index('FileTypeDel', table_name='libbook')
    op.drop_index('LangDel', table_name='libbook')
    op.drop_index('ibook', table_name='libgenre')
    op.drop_index('igenre', table_name='libgenre')
    op.drop_index('u', table_name='libgenre')
    op.drop_column('libgenre', 'Id')
    op.drop_index('meta', table_name='libgenrelist')
    op.alter_column('librate', 'Rate',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)
    op.drop_index('BookId', table_name='librate')
    op.drop_index('BookId1', table_name='librate')
    op.create_unique_constraint(None, 'librate', ['UserId'])
    op.create_unique_constraint(None, 'librate', ['BookId'])
    op.drop_column('librate', 'ID')
    op.alter_column('libseq', 'Level',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_table_comment(
        'libseqname',
        existing_comment='Список форм (1-100) и названий сериа',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'libseqname',
        'Список форм (1-100) и названий сериа',
        existing_comment=None,
        schema=None
    )
    op.alter_column('libseq', 'Level',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.add_column('librate', sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'librate', type_='unique')
    op.drop_constraint(None, 'librate', type_='unique')
    op.create_index('BookId1', 'librate', ['BookId'], unique=False)
    op.create_index('BookId', 'librate', ['BookId', 'UserId'], unique=True)
    op.alter_column('librate', 'Rate',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(length=1),
               existing_nullable=False)
    op.create_index('meta', 'libgenrelist', ['GenreMeta'], unique=False)
    op.add_column('libgenre', sa.Column('Id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False))
    op.create_index('u', 'libgenre', ['BookId', 'GenreId'], unique=True)
    op.create_index('igenre', 'libgenre', ['GenreId'], unique=False)
    op.create_index('ibook', 'libgenre', ['BookId'], unique=False)
    op.create_index('LangDel', 'libbook', ['Deleted', 'Lang'], unique=False)
    op.create_index('FileTypeDel', 'libbook', ['Deleted', 'FileType'], unique=False)
    op.create_index('BookDel', 'libbook', ['Deleted', 'BookId'], unique=True)
    op.alter_column('libbook', 'InfoCode',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('libbook', 'pmd5',
               existing_type=sa.String(length=32),
               type_=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=32),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('libbook', 'Modified',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("'2009-11-29 05:00:00'"))
    op.alter_column('libbook', 'md5',
               existing_type=sa.String(length=32),
               type_=sa.BINARY(length=32),
               existing_nullable=False)
    op.alter_column('libbook', 'Deleted',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=1),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('libbook', 'Year',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('libbook', 'FileType',
               existing_type=sa.String(length=4),
               type_=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=4),
               existing_nullable=False)
    op.alter_column('libbook', 'SrcLang',
               existing_type=sa.String(length=3),
               type_=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('libbook', 'LangEx',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('libbook', 'Lang',
               existing_type=sa.String(length=3),
               type_=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'ru'"))
    op.alter_column('libbook', 'Time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('email', 'libavtorname', ['Email'], unique=False)
    op.alter_column('libavtorname', 'MasterId',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('libavtorname', 'Gender',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=1),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.create_index('iav', 'libavtor', ['AvtorId'], unique=False)
    op.alter_column('libavtor', 'Pos',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_table('libbannotations')
    # ### end Alembic commands ###
